#Goal: Building a multi-job workflow from scratch with three jobs : build, test, and deploy
name: Multi-Jobs Workflow

on:
  push: 
    branches: [ "main" ]


# ENV VARIABLE GLOBAL SCOPE : available in all jobs and all the steps
env:
  GLOBAL_APP_NAME: "MyAmazingApp"  

jobs:

# 1. Build the job
  build:
    runs-on: ubuntu-latest

# Declare the output for this job to print date
    outputs:
      generated_date: ${{ steps.date_step.outputs.TODAYS_DATE }}

# ENV VARIABLE JOB SCOPE : available only inside the build job
    env:
      BUILD_ENVIRONMENT: "staging"
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4


      - name: Compile and Build Application
# Declare the variable at Step Level
        env:
          COMPILER_FLAGS: "-03"

      - id: date_step    
        run: |
          echo "Running build scripts ..."
          echo "Building the app: $GLOBAL_APP_NAME"
          echo "Environment is: $BUILD_ENVIRONMENT"
          echo "Using Flags: $COMPILER_FLAGS"
          CURRENT_DATE=$(date +'%Y-%m-%d')
          echo "TODAYS_DATE=$CURRENT_DATE" >> $GITHUB_OUTPUT
          echo "Generated Date in build job: $CURRENT_DATE"

      - name: Identity Check
        run: echo "This workflow was triggered by user ${{ github.actor }}"


# 2. Test the job (Runs only if the previous Build succeeds)

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Run the tests
        run: |
          echo "Executing the tests, Testing app is : $GLOBAL_APP_NAME"
      
      - name: Read Date from Build Job
        run: |
          echo "Date received from Build is: ${{ needs.build.outputs.generated_date }}"    
# 3. Deploying the job (Runs only if the Test succeeds)        
      
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Deploy to Production
        run: echo "Deploy applications..."




